apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-tvfo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-tvfo
    app.kubernetes.io/part-of: test-app-pqke
  name: nodejs-no-dockerfile-tvfo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-tvfo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-tvfo
    spec:
      containers:
      - image: quay.io/susdas_quay_org/build-e2e-hzrm-tenant/test-app-pqke/nodejs-no-dockerfile-tvfo@sha256:4205867ec58bcbfd98937208fa904c144646cb0b27bb92d9c318828b3c0ddfe6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
