apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-tvfo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-tvfo
    app.kubernetes.io/part-of: test-app-pqke
  name: nodejs-no-dockerfile-tvfo
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nodejs-no-dockerfile-tvfo
status:
  loadBalancer: {}
